import type { MainAnalysisResponse, PopupResponse } from './healthAnalysis';

// DEVELOPMENT ONLY: remove after the development API always provides an assessment.
// This fixture intentionally uses the same response types as the health-analysis endpoints.
export const devHealthAnalysisFallback = {
  analysis: {
    assessment_id: '00000000-0000-4000-8000-000000000001',
    headline: { title: '체성분 균형을 우선 관리해보세요' },
    summary: {
      title: '현재 건강 상태 요약',
      description: '체지방률과 혈당 수치를 함께 관리하면 건강 목표에 더 가까워질 수 있어요.',
    },
    goal: { text: '건강한 체성분과 일상 컨디션 유지' },
    strategy: {
      title: 'Auto-Fit 맞춤 제언',
      tags: ['체지방 관리', '근력 운동', '식습관 점검'],
      message: '주 3회 근력 운동과 규칙적인 식사로 체성분 균형을 만들어보세요.',
    },
    key_metric_keys: [
      'body_fat_percentage',
      'skeletal_muscle_mass_kg',
      'fasting_glucose',
    ],
    recommendation_reasons: [
      {
        title: '체중보다 체성분을 우선했어요',
        description: '체지방률과 골격근량을 함께 확인해 지속 가능한 운동 전략을 제안했어요.',
        evidence_metric_keys: ['body_fat_percentage', 'skeletal_muscle_mass_kg'],
      },
      {
        title: '혈당 관리도 함께 고려했어요',
        description: '공복혈당 수치를 참고해 식사와 운동의 균형을 제안했어요.',
        evidence_metric_keys: ['fasting_glucose'],
      },
    ],
    final_direction: { from: '체중 중심 관리', to: '체성분과 생활 습관 관리' },
  },
  popups: {
    assessment_id: '00000000-0000-4000-8000-000000000001',
    calculation_version: 'dev-fallback',
    body_composition_id: null,
    health_checkup_id: null,
    criteria_snapshot_available: true,
    metrics: [
      {
        key: 'body_fat_percentage',
        raw_value: '28.4',
        display_value: '28.4',
        unit: '%',
        value_origin: 'reported',
        measured_at: '2026-09-22',
        status: 'high',
        status_label: '높음',
        criteria_id: 'dev-body-fat',
        criteria_version: 'dev-1',
        criteria_type: '체성분 기준',
        source_ids: ['dev-source-body-composition'],
        applied_conditions: {},
        missing_fields: [],
        discrepancy: null,
        ranges: [
          { status: 'normal', min: '18', max: '28', min_inclusive: true, max_inclusive: false },
          { status: 'high', min: '28', min_inclusive: true },
        ],
      },
      {
        key: 'skeletal_muscle_mass_kg',
        raw_value: '20.8',
        display_value: '20.8',
        unit: 'kg',
        value_origin: 'reported',
        measured_at: '2026-09-22',
        status: 'normal',
        status_label: '정상',
        criteria_id: 'dev-muscle',
        criteria_version: 'dev-1',
        criteria_type: '체성분 기준',
        source_ids: ['dev-source-body-composition'],
        applied_conditions: {},
        missing_fields: [],
        discrepancy: null,
        ranges: [
          { status: 'low', max: '18', max_inclusive: false },
          { status: 'normal', min: '18', max: '24', min_inclusive: true, max_inclusive: true },
          { status: 'high', min: '24', min_inclusive: false },
        ],
      },
      {
        key: 'fasting_glucose',
        raw_value: '104',
        display_value: '104',
        unit: 'mg/dL',
        value_origin: 'reported',
        measured_at: '2026-09-22',
        status: 'caution',
        status_label: '주의',
        criteria_id: 'dev-glucose',
        criteria_version: 'dev-1',
        criteria_type: '혈당 기준',
        source_ids: ['dev-source-glucose'],
        applied_conditions: {},
        missing_fields: [],
        discrepancy: null,
        ranges: [
          { status: 'normal', max: '99', max_inclusive: true },
          { status: 'caution', min: '100', max: '125', min_inclusive: true, max_inclusive: true },
          { status: 'high', min: '126', min_inclusive: true },
        ],
      },
    ],
    interpretation: {
      rule_id: 'dev-fallback-interpretation',
      text: '체성분과 혈당 지표를 함께 고려한 개발용 분석 결과입니다.',
      evidence_metric_keys: [
        'body_fat_percentage',
        'skeletal_muscle_mass_kg',
        'fasting_glucose',
      ],
    },
    sources: [
      {
        source_id: 'dev-source-body-composition',
        publisher: '개발용 참고 자료',
        title: '체성분 관리 기준',
        source_type: 'development_fixture',
        applied_excerpt_summary: '체지방률과 골격근량을 함께 확인하는 기준입니다.',
        url: null,
        published_at: null,
        revised_at: null,
        verified_at: '2026-09-22',
        applied_metric_keys: ['body_fat_percentage', 'skeletal_muscle_mass_kg'],
      },
      {
        source_id: 'dev-source-glucose',
        publisher: '개발용 참고 자료',
        title: '공복혈당 관리 기준',
        source_type: 'development_fixture',
        applied_excerpt_summary: '공복혈당 수치를 생활 습관 관리에 참고하는 기준입니다.',
        url: null,
        published_at: null,
        revised_at: null,
        verified_at: '2026-09-22',
        applied_metric_keys: ['fasting_glucose'],
      },
    ],
  },
} satisfies { analysis: MainAnalysisResponse; popups: PopupResponse };
